
# This file was created locally after connecting to Supabase project iczxhmzwjopfdvbxwzjs

project_id = "iczxhmzwjopfdvbxwzjs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

# Update this if you want to have your functions called from the Edge Function
[functions.generate-report]
verify_jwt = true

[functions.impersonate-user]
verify_jwt = true
